language: go

go:
    - 1.2
    - tip

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/kr/godep
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - godep go test -race ./...
  - godep go test -cover ./...
  
matrix:
    allow_failures:
        - go: tip